server:
  port: 8081
db:
  connection: "type de connection"
  host: "128.1.1.0"
  port: 3306
  uri: "jdbc:mysql://srv-bdens.insa-toulouse.fr:3306/projet_gei_053"
  name: "projet_gei_053"
  login: "projet_gei_053"
  pwd: "Aarei9hi"
